### ISSUE TITLE
in '03-Snowpark-UDF-Deployment' predictions using SQL missing COUNT parameter

### ISSUE THREAD

**Issue by olvgrolle** [Snowflake-Labs/sfguide-getting-started-snowpark-python#1]
in notebook '03-Snowpark-UDF-Deployment' in the section: 

**if we want to do the prediction using SQL**
the SQL query should be the following: 

%%time
session.sql(' select customerid,churnvalue, \
            predict_churn_model(ARRAY_CONSTRUCT( \
                                    GENDER, \
                                    COUNT,\
                                    SENIORCITIZEN, \
                                    PARTNER, \
                                    DEPENDENTS, \
                                    PHONESERVICE, \
                                    MULTIPLELINES,  \
                                    INTERNETSERVICE,  \
                                    ONLINESECURITY,  \
                                    ONLINEBACKUP, \
                                    DEVICEPROTECTION,  \
                                    TECHSUPPORT,  \
                                    STREAMINGTV,  \
                                    STREAMINGMOVIES, \
                                    CONTRACT,  \
                                    PAPERLESSBILLING,  \
                                    PAYMENTMETHOD,  \
                                    TENUREMONTHS, \
                                    MONTHLYCHARGES,  \
                                    TOTALCHARGES)) as Churn_prediction \
                                    from train_dataset sample (10 rows)').show()

instead of: 

%%time
session.sql(' select customerid,churnvalue, \
            predict_churn_model(ARRAY_CONSTRUCT( \
                                    GENDER, \
                                    SENIORCITIZEN, \
                                    PARTNER, \
                                    DEPENDENTS, \
                                    PHONESERVICE, \
                                    MULTIPLELINES,  \
                                    INTERNETSERVICE,  \
                                    ONLINESECURITY,  \
                                    ONLINEBACKUP, \
                                    DEVICEPROTECTION,  \
                                    TECHSUPPORT,  \
                                    STREAMINGTV,  \
                                    STREAMINGMOVIES, \
                                    CONTRACT,  \
                                    PAPERLESSBILLING,  \
                                    PAYMENTMETHOD,  \
                                    TENUREMONTHS, \
                                    MONTHLYCHARGES,  \
                                    TOTALCHARGES)) as Churn_prediction \
                                    from train_dataset sample (10 rows)').show()

**Comment by sfc-gh-cbaechtold** [comment]
Thank you for finding this- issue has been resolved with 0fd6a8e
